#**************** SIGNOS HC ***********************#
signos_list:
    pattern:  /signos/{id}/list
    defaults: { _controller: HcBundle:Signos:list }
    
signos_edit:
    pattern:  /signos/{id}/edit
    defaults: { _controller: HcBundle:Signos:edit }
    options: 
        expose: true
    
signos_update:
    pattern:  /signos/{id}/update
    defaults: { _controller: HcBundle:Signos:update }
    
signos_examen:
    pattern:  /signos/{id}/examen
    defaults: { _controller: HcBundle:Signos:listExamenes }
    
signos_signos:
    pattern:  /signos/{id}/signos
    defaults: { _controller: HcBundle:Signos:signos}
    
#**************** EXAMEN HC ***********************#

hcExamen_new:
    pattern:  /hcExamen/{factura}/new
    defaults: { _controller: HcBundle:HcExamen:new }
    options:
        expose: true

hc_hcExamen:
    pattern:  /hcExamen/save
    defaults: { _controller: HcBundle:HcExamen:hcExamen }
    requirements:
        _method:  POST
    
hc_editHcExamen:
    pattern:  /{id}/editHcExamen
    defaults: { _controller: HcBundle:HcExamen:editHcExamen }
    
hc_delHcExamen:
    pattern:  /hcExamen/delete
    defaults: { _controller: HcBundle:HcExamen:delHcExamen }
    requirements:
        _method:  POST
    
hc_updateHcExamen:
    pattern:  /{id}/updateHcExamen
    defaults: { _controller: HcBundle:HcExamen:updateHcExamen }
    
hc_examen_cronologico:
    pattern:  /examen/cronologico
    defaults: { _controller: HcBundle:HcExamen:cronologicoExamenes }
    requirements:
        _method:  POST
        
hc_examen_upd_ajax:
    pattern:  /hcExamen/ajaxupd
    defaults: { _controller: HcBundle:HcExamen:ajaxUpdHcExamen }
    requirements:
        _method:  POST
    
#**************** MEDICAMENTO HC ***********************#
hc_hcMedi:
    pattern:  /hcMedi/save
    defaults: { _controller: HcBundle:HcMedicamento:hcMedi }
    requirements:
        _method:  POST
    
hc_editHcMedi:
    pattern:  /{id}/{factura}/editHcMedi
    defaults: { _controller: HcBundle:HcMedicamento:editHcMedi }
    
hc_delHcMedi:
    pattern:  /delHcMedi/delete
    defaults: { _controller: HcBundle:HcMedicamento:delHcMedi }
    requirements:
        _method:  POST
    
hc_updateHcMedi:
    pattern:  /{id}/updateHcMedi
    defaults: { _controller: HcBundle:HcMedicamento:updateHcMedi }
#**************** DIAGNOSTICO HC ***********************#

hc_hcCie:
    pattern:  /hcCie/save
    defaults: { _controller: HcBundle:HcCie:hcCie }
    requirements:
        _method:  POST
        
hc_delHcCie:
    pattern:  /delHcCie/delete
    defaults: { _controller: HcBundle:HcCie:delHcCie }
    requirements:
        _method:  POST
       
#************** HistoriClinica ***************#
hc_new:
    pattern:  /{id}/new
    defaults: { _controller: HcBundle:Hc:new } 

hc_autoSave:
    pattern:  /autoSave/{id}
    defaults: { _controller: HcBundle:Hc:autoSave }
    options:
        expose: true   
    
hc_save:
    pattern:  /{id}/save
    defaults: { _controller: HcBundle:Hc:save }
    
hc_edit:
    pattern:  /{id}/edit
    defaults: { _controller: HcBundle:Hc:edit }
    options: 
        expose: true
    
hc_update:
    pattern:  /{id}/update
    defaults: { _controller: HcBundle:Hc:update }
    
hc_search:
    pattern:  /search
    defaults: { _controller: HcBundle:Hc:search }

hc_paginator:
    pattern:  /{id}/lisHc
    defaults: { _controller: HcBundle:Hc:paginator }
    
hc_list:
    pattern:  /listHc
    defaults: { _controller: HcBundle:Hc:list }

hc_view:
    pattern:  /verHc/{id}
    defaults: { _controller: HcBundle:Hc:ver } 
    
hc_imprime:
    pattern:  /Impresion/{factura}
    defaults: { _controller: HcBundle:Hc:imprimir }

hc_ajaxupdate:
    pattern:  /update/{id}
    defaults: { _controller: HcBundle:Hc:update }
#************** Examen ***************#
examen_examen:
    pattern:  /examen/examen
    defaults: { _controller: HcBundle:Examen:examen }
        
examen_new:
    pattern:  /examen/newExamn
    defaults: { _controller: HcBundle:Examen:new }
    
examen_save:
    pattern:  /examen/saveExamn
    defaults: { _controller: HcBundle:Examen:save }
    
examen_edit:
    pattern:  /examen/{id}/editExamn
    defaults: { _controller: HcBundle:Examen:edit }
    
examen_update:
    pattern:  /examen/{id}/updateExamn
    defaults: { _controller: HcBundle:Examen:update }
    
examen_list:
    pattern:  /examen/listExamn
    defaults: { _controller: HcBundle:Examen:list }
    
examen_userExamen:
    pattern:  /examen/{usuario}/{examen}/userExamen
    defaults: { _controller: HcBundle:Examen:userExamen }
    
examen_deleteUserExamen:
    pattern:  /examen/{usuario}/{examen}/deleteUserExamen
    defaults: { _controller: HcBundle:Examen:deleteUserExamen }
    
userExamen_new_ajax:
    pattern:  /examen/userExamen/ajax/new
    defaults: { _controller: HcBundle:Examen:ajaxUserExamen }
    requirements:
        _method:  POST
    
#************** Medicamento *******************#
medicamento_new:
    pattern:  /medicamento/nuevo
    defaults: { _controller: HcBundle:Medicamento:new }
    
medicamento_save:
    pattern:  /medicamento/salvar
    defaults: { _controller: HcBundle:Medicamento:save }
    
medicamento_list:
    pattern:  /medicamento/list
    defaults: { _controller: HcBundle:Medicamento:list }
    
medicamento_edit:
    pattern:  /medicamento/{id}/edit
    defaults: { _controller: HcBundle:Medicamento:edit}
    
medicamento_update:
    pattern:  /medicamento/{id}/update
    defaults: { _controller: HcBundle:Medicamento:update }

medicamento_search:
    pattern:  /medicamento/search
    defaults: { _controller: HcBundle:Medicamento:search }
    
userMx_new_ajax:
    pattern:  /examen/userMed/ajax/new
    defaults: { _controller: HcBundle:Medicamento:ajaxUserMx }
    requirements:
        _method:  POST
    
#************** Diagnostico ***************#

dx_new:
    pattern:  /dx/nuevo
    defaults: { _controller: HcBundle:Diagnostico:newDx }
    
dx_save:
    pattern:  /dx/salvar
    defaults: { _controller: HcBundle:Diagnostico:saveDx }

dx_edit:
    pattern:  /dx/{id}/edit
    defaults: { _controller: HcBundle:Diagnostico:editDx }
    
dx_update:
    pattern:  /dx/{id}/update
    defaults: { _controller: HcBundle:Diagnostico:updateDx }
    
dx_list:
    pattern:  /dx/lista
    defaults: { _controller: HcBundle:Diagnostico:listDx }
    
dx_search:
    pattern:  /dx/search
    defaults: { _controller: HcBundle:Diagnostico:searchDx }

dx_userDx:
    pattern: /dx/diagnostico
    defaults: { _controller: HcBundle:Diagnostico:userDx }
    
dx_saveUserDx:
    pattern: /dx/{usuario}/{cie}/saveUserDx
    defaults: { _controller: HcBundle:Diagnostico:saveUserDx }
    
dx_deleteUserDx:
    pattern: /dx/{usuario}/{cie}/deleteUserDx
    defaults: { _controller: HcBundle:Diagnostico:deleteUserDx }
    
userDx_new_ajax:
    pattern:  /dx/userDx/ajax/new
    defaults: { _controller: HcBundle:Diagnostico:ajaxUserDx }
    requirements:
        _method:  POST
    
#****************** formato no post CTC *********************#
ctc_noPos:
    pattern:  /ctc/{id}/noPos
    defaults: { _controller: HcBundle:Ctc:noPos }

ctc_new:
    pattern:  /ctc/{id}/new
    defaults: { _controller: HcBundle:Ctc:new }
    
ctc_save:
    pattern:  /ctc/{hm}/save
    defaults: { _controller: HcBundle:Ctc:save }

ctc_edit:
    pattern:  /ctc/{id}/edit
    defaults: { _controller: HcBundle:Ctc:edit }
    
ctc_update:
    pattern:  /ctc/{id}/update
    defaults: { _controller: HcBundle:Ctc:update }
    
ctc_list:
    pattern:  /ctc/{id}/list
    defaults: { _controller: HcBundle:Ctc:list }  
    
ctc_search:
    pattern:  /ctc/search
    defaults: { _controller: HcBundle:Ctc:search }
    
ctc_buscar:
    pattern:  /ctc/consultar
    defaults: { _controller: HcBundle:Ctc:busqueda }

ctc_imprimir:
    pattern:  /ctc/{id}/imprimir
    defaults: { _controller: HcBundle:Ctc:imprimir }

    
#****************** HC Estetica *********************#

HcEstetica_new:
    pattern:  /estetica/{hc}/New
    defaults: { _controller: HcBundle:HcEstetica:new }
    
HcEstetica_save:
    pattern:  /estetica/{hc}/Save
    defaults: { _controller: HcBundle:HcEstetica:save}
    
HcEstetica_edit:
    pattern:  /estetica/{hc}/Edit
    defaults: { _controller: HcBundle:HcEstetica:edit }

HcEstetica_view:
    pattern:  /estetica/{hc}/View
    defaults: { _controller: HcBundle:HcEstetica:view }
    
HcEstetica_impresa:
    pattern:  /estetica/{hcEstetica}/formatoImpreso
    defaults: { _controller: HcBundle:HcEstetica:impreso }
    
HcEstetica_update:
    pattern:  /estetica/{estetica}/Update
    defaults: { _controller: HcBundle:HcEstetica:update }
    
#****************** Files *********************#

file_upload:
    pattern:  /file/{estetica}/upload
    defaults: { _controller: HcBundle:Files:upload }
    
file_new:
    pattern:  /file/{estetica}/newFile
    defaults: { _controller: HcBundle:Files:new }
    
file_edit:
    pattern:  /file/{file}/editFile
    defaults: { _controller: HcBundle:Files:edit}
    
file_update:
    pattern:  /file/{file}/saveFile
    defaults: { _controller: HcBundle:Files:update }
    
file_showImagens:
    pattern:  /file/{estado}/{estetica}/showImagens
    defaults: { _controller: HcBundle:Files:showImagens }
    
file_upImagen:
    pattern:  /file/up/imagen
    defaults: { _controller: HcBundle:Files:upImagen }
    requirements:
        _method:  POST
    
#****************** Impresos *********************#

impreso_firma:
    pattern:  /impresion/{hc}/{option}/certi
    defaults: { _controller: HcBundle:Impresos:impresion }
    
impreso_list:
    pattern:  /impresion/{hc}/certificados
    defaults: { _controller: HcBundle:Impresos:list }